### ISSUE TITLE
IE/Edge compatibility issues

### ISSUE THREAD

**Issue by allisondeluca** [VincentCharpentier/krousel#1]
Errors and carousel is stuck on IE and Edge
Object doesn't support property or method 'values' on line: p=Object.values(t)

**Comment by VincentCharpentier** [comment]
Hi @allisondeluca ,

Object.values is part of ES 2017, which is already old.
I'm not sure it is a good idea to polyfill ES 2017+ because that would add a lot of weight into the bundle.

I will add a mention in the readme regarding browser support at some point, I don't have a precise list yet.

Anyway from what I can tell using caniuse.com (https://caniuse.com/#feat=object-values), this plugin won't work in IE or Edge 13 and below.

You can try to use babel-polyfill or core-js directly to polyfill yourself the missing browser features.
Another solution also viable would be to switch to Slick which is built on jQuery and thus should be ok with IE and Edge
